# Generated by Django 4.2.10 on 2024-02-19 19:27

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0027_created_updated_everywhere"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speakerinformation",
            name="text",
            field=tinymce.models.HTMLField(),
        ),
    ]
