# Generated by Django 4.2.10 on 2024-02-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0027_created_updated_everywhere"),
    ]

    operations = [
        migrations.AddField(
            model_name="speakerprofile",
            name="avatar_copyright",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="speakerprofile",
            name="avatar_source",
            field=models.TextField(null=True),
        ),
    ]
