# Generated by Django 4.2.10 on 2024-02-19 09:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0075_increase_resource_link_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="cfp",
            name="rtf",
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
