# Generated by Django 4.2.10 on 2024-02-21 18:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0075_increase_resource_link_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cfp",
            name="text",
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
