# Generated by Django 4.2.10 on 2024-02-19 11:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0076_cfp_rtf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cfp",
            name="rtf",
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
