# Generated by Django 4.2.10 on 2024-02-19 13:03

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0077_alter_cfp_rtf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cfp",
            name="rtf",
        ),
        migrations.AlterField(
            model_name="cfp",
            name="text",
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
