# Generated by Django 4.2.10 on 2024-02-22 10:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0077_alter_track_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="abstract",
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="description",
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
