# Generated by Django 4.2.10 on 2024-02-19 16:54

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0078_remove_cfp_rtf_alter_cfp_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="abstract",
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
