# Generated by Django 4.2.10 on 2024-02-19 18:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0079_alter_submission_abstract"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="description",
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
