# Generated by Django 2.2.9 on 2020-01-24 12:13

from django.db import migrations, models
import eventyay.person.models.information
import eventyay.person.models.user


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0020_auto_20180922_0511"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speakerinformation",
            name="resource",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=eventyay.person.models.information.resource_path,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=eventyay.person.models.user.avatar_path
            ),
        ),
    ]
