# Generated by Django 4.2.10 on 2024-02-19 16:29

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0035_created_updated_everywhere"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="featured_sessions_text",
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
