name: Documentation

on:
  push:
    branches: [ development ]
    paths:
      - 'doc/**'
  pull_request:
    branches: [ development ]
    paths:
      - 'doc/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  spelling:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: ".github/workflows/python-version.txt"
          cache: "pip"
      - name: Install system packages
        run: |
          sudo apt update
          sudo apt install enchant-2 hunspell aspell-en
      - name: Install Dependencies
        run: python -m pip install -Ur doc/requirements.txt
      - name: Spellcheck docs
        run: make spelling
        working-directory: ./doc
      - name:
        run: '[ ! -s _build/spelling/output.txt ]'
        working-directory: ./doc

  linkcheck:
    name: Linkcheck
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: ".github/workflows/python-version.txt"
          cache: "pip"
      - name: Install Dependencies
        run: pip3 install -Ur doc/requirements.txt
      - name: Linkcheck docs
        run: make linkcheck
        working-directory: ./doc
